services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metering
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # inbox UI
      - "1025:1025" # SMTP

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/metering
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      SMTP_URL: smtp://mailpit:1025
      ALERT_FROM_EMAIL: no-reply@localhost
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/metering
      CELERY_BROKER_URL: redis://redis:6379/0
      SMTP_URL: smtp://mailpit:1025
      ALERT_FROM_EMAIL: no-reply@localhost
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: .venv/bin/celery -A app.worker.celery_app:celery_app worker --loglevel=info

  beat:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/metering
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: .venv/bin/celery -A app.worker.celery_app:celery_app beat --loglevel=info

volumes:
  pgdata:
